print("tmp1")
print("tmp1")print("tmp1")
print("tmp1")print("tmp1")print("tmp1")
print("tmp1")print("tmp1")print("tmp1")print("tmp1")
print("tmp1")print("tmp1")print("tmp1")print("tmp1")print("tmp1")
