print("tmp2")
print("tmp2");print("tmp2")
print("tmp2");print("tmp2");print("tmp2")
print("tmp2");print("tmp2");print("tmp2");print("tmp2")
print("tmp2");print("tmp2");print("tmp2");print("tmp2");print("tmp2")
print("tmp2")
print("tmp2");print("tmp2")
print("tmp2");print("tmp2");print("tmp2")
print("tmp2");print("tmp2");print("tmp2");print("tmp2")
print("tmp2");print("tmp2");print("tmp2");print("tmp2");print("tmp2")
print("tmp2")
print("tmp2");print("tmp2")
print("tmp2");print("tmp2");print("tmp2")
print("tmp2");print("tmp2");print("tmp2");print("tmp2")
print("tmp2");print("tmp2");print("tmp2");print("tmp2");print("tmp2")

